#!/bin/bash
#SBATCH --job-name=plot_auc_summary
#SBATCH --output=outputs/plot_auc_summary.out
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu
#SBATCH --mem=32000
#SBATCH --time=1:00:00

# Load the Anaconda module
module load anaconda3/2024.06/gcc-13.2.0
module load cuda/12.2.1/gcc-11.2.0

# Activate the Conda environment
source activate base_ml

pip freeze > requirements_old.txt

# Base directory where metrics.json files are stored
# Looking at the folder structure, 'Images/Alignment_early_linear_5runs_batch512' seems to be relative to the repo root
# If running on cluster, this folder might be generated by previous jobs in the same workspace
BASE_DIR="Images/Alignment_early_linear_5runs_batch512"

# Output directory for the summary plot
OUTPUT_DIR="Images/Summary"
mkdir -p "$OUTPUT_DIR"

echo "Running plot_auc_summary.py..."
echo "Looking for metrics in: $BASE_DIR"

python scripts/plot_auc_summary.py \
    --base_dir "$BASE_DIR" \
    --output_dir "$OUTPUT_DIR"
